### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by nicolasvahidzein** [tommyle/commit_ai#1]
Hello, i wanted to test your tool but after importing the packages i got an error:

C:\Users\Nicolas Zein\Desktop\dddd\commit_ai>dart compile exe lib/commit_ai.dart -o build/commit_ai
Info: Compiling with sound null safety.
Error: AOT compilation failed
PathNotFoundException: Cannot open file, path = 'c:\users\nicolas zein\desktop\dddd\commit_ai\build\commit_ai' (OS Error: The system cannot find the path specified.
, errno = 3)

**Comment by tommyle** [comment]
Do you have a build folder? Try to create the build folder first.

**Comment by nicolasvahidzein** [comment]
That works. Thanks buddy.
