### ISSUE TITLE
Cannot run on windows

### ISSUE THREAD

**Issue by nicolasvahidzein** [tommyle/commit_ai#2]
Hello,

when i compiled the code i get a file "commit_ai" with no extension and when i try to run:

./commit_ai --set_api_key

from either the build folder or the root folder nothing happens.

C:\Users\Nicolas Zein\Desktop\commitai\build>commit_ai --set_api-key
'commit_ai' is not recognized as an internal or external command,
operable program or batch file.

**Comment by tommyle** [comment]
Might have to use the exe extension or omit the -o argument.
Take a look here: https://dart.dev/tools/dart-compile

**Comment by nicolasvahidzein** [comment]
That worked thanks. I moved the exe on windows from the lib folder the build folder and i was able to set the API key and i will now test it in prod. I'm guessing we need to move the file to the repo? At the root? I suggesting updating the readme to explain the 2 steps which are: adding manually the build folder and omitting the -o flag on windows which might be buggy. I'll return to comment once tested. Cheers buddy.
